/vis/open OGL
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/autoRefresh true

/MyCube/CubeDistance 2.7
/MyCube/CubeSide 0.25

/MySource/SourceHeight 1.0

/run/initialize

/vis/drawVolume
/vis/viewer/flush
/vis/scene/add/volume
/vis/scene/add/trajectories smooth
/vis/scene/add/scale 10 cm
/vis/scene/add/axes 
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate
